In [1]:
#!/usr/bin/env python

In [2]:
import os
import sys
if os.path.exists('/home/chieh/code/wuML'):
	sys.path.insert(0,'/home/chieh/code/wuML')

In [3]:
import wuml 
from wuml import jupyter_print

In [4]:
data = wuml.make_classification_data( n_samples=300, n_features=6, n_informative=3, n_classes=3)

In [5]:
tenF_LDA_LR = wuml.ten_folder_classifier(data, classifier='SVM')
tenF_LDA_LR.show_results()

Running fold :1
Running fold :2
Running fold :3
Running fold :4
Running fold :5
Running fold :6
Running fold :7
Running fold :8
Running fold :9
Running fold :10

In [6]:
jupyter_print('\nIf we use the entire 10 models and obtain labels by voting, we get')
ӯ = tenF_LDA_LR(data)
summary = wuml.summarize_classification_result(data.Y, ӯ)

If we use the entire 10 models and obtain labels by voting, we get
Classification Accuracy: 0.7900